### ISSUE TITLE
The class cannot be injected as a parameter.If you have time please answer for me, thank you very much.

### ISSUE THREAD

**Issue by 1103036128** [leangen/graphql-spqr-samples#6]
I have a problem. When I made a mistake in the method of executing the query, I probably found the reason that I could not recognize the fatigue. The error is as follows:
public List<Queue> test(@GraphQLArgument(name = "Queue") Queue queue)
Caused by: java.lang.NullPointerException: null
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'queueGraphQLController' defined in file [G:\360data\重要数据\桌面\ewe-hr\ewe-hr\workorder\target\classes\com\ewe\workorder\controller\QueueGraphQLController.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ewe.workorder.controller.QueueGraphQLController]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.ewe.Application.main(Application.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ewe.workorder.controller.QueueGraphQLController]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	... 23 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.supports(NonNullMapper.java:52)
	at io.leangen.graphql.generator.mapping.TypeMapperRepository.lambda$getTypeMapper$46(TypeMapperRepository.java:19)
	at io.leangen.graphql.generator.mapping.TypeMapperRepository$$Lambda$111/1522223339.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1336)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at io.leangen.graphql.generator.mapping.TypeMapperRepository.getTypeMapper(TypeMapperRepository.java:19)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLInputType(OperationMapper.java:180)
	at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLInputType(ListMapper.java:28)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLInputType(OperationMapper.java:181)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLInputField(OperationMapper.java:165)
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$toGraphQLInputType$191(ObjectTypeMapper.java:62)
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper$$Lambda$213/1351282551.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLInputType(ObjectTypeMapper.java:61)
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLInputType(ObjectTypeMapper.java:29)
	at io.leangen.graphql.generator.mapping.common.CachingMapper.graphQLInputType(CachingMapper.java:38)
	at io.leangen.graphql.generator.mapping.common.AbstractionCollectingMapper.toGraphQLInputType(AbstractionCollectingMapper.java:34)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLInputType(OperationMapper.java:181)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLArgument(OperationMapper.java:189)
	at io.leangen.graphql.generator.OperationMapper.lambda$toGraphQLOperation$22(OperationMapper.java:129)
	at io.leangen.graphql.generator.OperationMapper$$Lambda$150/756575341.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1359)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLOperation(OperationMapper.java:129)
	at io.leangen.graphql.generator.OperationMapper.lambda$generateQueries$20(OperationMapper.java:82)
	at io.leangen.graphql.generator.OperationMapper$$Lambda$110/512219973.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1359)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.leangen.graphql.generator.OperationMapper.generateQueries(OperationMapper.java:83)
	at io.leangen.graphql.generator.OperationMapper.<init>(OperationMapper.java:67)
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:684)
	at com.ewe.workorder.controller.QueueGraphQLController.<init>(QueueGraphQLController.java:72)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 25 common frames omitted

**Comment by kaqqao** [comment]
All this stacktrace tells me is that there's a null pointer in `NonNullMapper#supports`. I think I remember some older version of SPQR had a bug that could cause this to happen. So as a first order of business, make sure you're at version 0.9.6.

If you're still having issues after the upgrade, you'll have to give more details. Put a breakpoint in `NonNullMapper#supports` and see what type causes it to throw an exception.

**Comment by 1103036128** [comment]
My question is still there, my breakpoint tells me that my entity class can't find it, it's empty.
This is my code:
`@GraphQLMutation(name = "createQueue")
    public Queue createQueue(@GraphQLArgument(name = "Queue") Queue queue){
    	LOGGER.info(queue.getName());
    	return queueService.addqueue(queue);
    }  `
Here is my request:
`{createQueue (Queue:{name:'now Test'})}`
Result:
Validation error of type SubSelectionRequired: Sub selection required for type Queue of field .
Validation error of type UnknownArgument: Unknown field argument Queue.

**Comment by 1103036128** [comment]
Supplement:
`Validation error of type SubSelectionRequired: Sub selection required for type Queue of field createQueue.`

**Comment by kaqqao** [comment]
This looks like a whole different question. The first was an exception in schema creation, this one is simply an invalid query.

The operation returns an object type `Queue` (not a scalar nor a list of scalars), so a sub-query (sub-selection) is required: 

```graphql
Mutation createQueue {
    createQueue (Queue:{name:"now Test"}) {
        name
    }
}
```
This is presuming `Queue` is a some custom class with a `name` field, same as in your input, and not `java.util.Queue`.

**Comment by kaqqao** [comment]
Also notice the `Mutation` keyword is mandatory for mutations and double quotes around strings.
Validation errors like the one above mean the query is bad.

**Comment by 1103036128** [comment]
Thank you for solving the problem for me, I will study hard, my problem is solved. I wish you good luck!

**Comment by kaqqao** [comment]
Cheers! Glad you got it sorted.
